### ISSUE TITLE
Stream can be called only once

### ISSUE THREAD

**Issue by mitissen** [fzyzcjy/flutter_rust_bridge#2372] opened 2024-10-25 10:10 UTC
Hi, i have a problem, that i can call a function using StreamSink<T> on the rust side as parameter only once in dart.

Example:

```rust
pub fn my_method(
    sink: StreamSink<String>) {
   // Call sink.add(..) 
}
```

At the dart side:

```dart
Future<void> another_method(ValueSetter<String> callback) {
    // init rustLib 
     await for (final event in my_method()) {
      callback(event)
    }
}
```

I call the `another_method` in my flutter app. 
I works without a problem i can show a progress bar progress by using the callback in my UI.

BUT the desired behavior happens only the first time i call `another_method`.
If i call `another_method` a second time the stream is already completed but the rust part is executed successfully.

So i see no progress bar progressing the second time :-)

Is this desired behavior because its a single subscription stream? But the stream is created every time the method is called, or am I wrong?

I've already tried closing the subscription and creating a new one every time `another_method` is called, but that doesn't seem to help

How can i call this function multiple times by using streams?

Best regards

**Comment by fzyzcjy** [comment] 2024-10-25 11:13
Hi, could you please provide a minimal reproducible sample? 

If you call `my_method` multi times, *each* time it should have a separate stream and thus the dart callback be called separately.

**Comment by mitissen** [comment] 2024-10-25 17:14
Now i know that my assumption was right.  Thank you for that! I will try to create a small repro.

**Comment by fzyzcjy** [comment] 2024-10-25 23:15
You are welcome! Feel free to ping me when you have a repro

**Comment by mitissen** [comment] 2024-10-28 06:48
Here is my repro

[flutter_rust_bridge_playground-main.zip](https://github.com/user-attachments/files/17538369/flutter_rust_bridge_playground-main.zip)

I think i find a solution to the problem. But i think it could still be interessting:

```rust
use std::{thread::sleep, time::Duration};

use flutter_rust_bridge::frb;
use once_cell::sync::OnceCell;

use crate::frb_generated::StreamSink;

#[flutter_rust_bridge::frb(sync)] // Synchronous mode for simplicity of the demo
pub fn greet(name: String) -> String {
    format!("Hello, {name}!")
}

#[flutter_rust_bridge::frb(init)]
pub fn init_app() {
    // Default utilities - feel free to customize
    flutter_rust_bridge::setup_default_user_utils();
}

#[frb(ignore)]
fn delegate(word: String, current: i32, max: i32) {
    MEM.get()
        .unwrap()
        .add(Progress { word, current, max })
        .unwrap();
}

static MEM: OnceCell<StreamSink<Progress>> = OnceCell::new();

pub struct Progress {
    pub current: i32,
    pub max: i32,
    pub word: String,
}

pub fn words_oncecell(sink: StreamSink<Progress>) {
    MEM.get_or_init(|| sink);
    inner_other(delegate);
}

pub fn words(sink: StreamSink<Progress>) {
    inner(|word, current, max| sink.add(Progress { word, current, max }).unwrap())
}

fn inner<T: Fn(String, i32, i32)>(callback: T) {
    callback("Hello".to_owned(), 1, 4);
    sleep(Duration::from_secs(3));
    callback("Peter".to_owned(), 2, 4);
    sleep(Duration::from_secs(1));
    callback("Hans".to_owned(), 3, 4);
    sleep(Duration::from_secs(2));
    callback("Robert".to_owned(), 4, 4);
}
fn inner_other(callback: fn(word: String, current: i32, max: i32)) {
    callback("Hello".to_owned(), 1, 4);
    sleep(Duration::from_secs(3));
    callback("Peter".to_owned(), 2, 4);
    sleep(Duration::from_secs(1));
    callback("Hans".to_owned(), 3, 4);
    sleep(Duration::from_secs(2));
    callback("Robert".to_owned(), 4, 4);
}
```

My original code was using `words_oncecell` function with oncecell. And this seems caused the error.

Now i'am using the approach used in the `words`function and it works as expected!

**Comment by fzyzcjy** [comment] 2024-10-28 13:49
> My original code was using words_oncecell function with oncecell. And this seems caused the error.

Not checked into the details (the minimal sample seems still a bit long and can be reduced if needed), but it seems that "once" cell means it will only initialize *once*. Thus, the second time you call it, it will not be stored. Thus the stream related things only appear once.

Btw, instead of global variables (e.g. the OnceCell), you can use methods attached to structs.

**Comment by fzyzcjy** [comment] 2024-11-05 00:43
Close since this seems to be solved, but feel free to reopen if you have any questions!

**Closed by fzyzcjy** 2024-11-05 00:43 UTC
Labels: awaiting
