### ISSUE TITLE
[Bug] flutter_rust_bridge_codegen doesn't work

### ISSUE THREAD

**Issue by NightBlaze** [fzyzcjy/flutter_rust_bridge#1446] opened 2023-12-18 13:46 UTC
### Describe the bug

```
-> % flutter_rust_bridge_codegen create my_app
error: unexpected argument 'my_app' found

Usage: flutter_rust_bridge_codegen [OPTIONS] --rust-input <RUST_INPUT>... --dart-output <DART_OUTPUT>...
       flutter_rust_bridge_codegen [CONFIG_FILE]

For more information, try '--help'.
```

```
-> % flutter_rust_bridge_codegen --version
flutter_rust_bridge_codegen 1.82.6
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
-> % RUST_LOG=debug flutter_rust_bridge_codegen create my_app
error: unexpected argument 'my_app' found

Usage: flutter_rust_bridge_codegen [OPTIONS] --rust-input <RUST_INPUT>... --dart-output <DART_OUTPUT>...
       flutter_rust_bridge_codegen [CONFIG_FILE]

For more information, try '--help'.
```
```


### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

macOS

### Version of `flutter_rust_bridge_codegen`

1.82.6

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-x64, locale ru-RU)
    • Flutter version 3.16.3 on channel stable at /Users/<user>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (12 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/<user>/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/<user>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1.2 23B92 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Version of `clang++`

15.0.0 (clang-1500.1.0.2.5)

**Comment by fzyzcjy** [comment] 2023-12-18 13:53
Yes, because 2.0 is not released yet!

**Comment by fzyzcjy** [comment] 2023-12-18 14:02
Btw I plan to release 2.0.0-dev.1 tomorrow (if possible). But expect some rough edges - since I cannot add more tests *before* 2.x prerelease is published, so I can only do that *after* the first prerelease.

**Comment by OnClickListener2048** [comment] 2023-12-18 14:42
same here, but the doc already has v2 version.

**Comment by OnClickListener2048** [comment] 2023-12-18 14:44
> Btw I plan to release 2.0.0-dev.1 tomorrow (if possible). But expect some rough edges - since I cannot add more tests _before_ 2.x prerelease is published, so I can only do that _after_ the first prerelease.

I did serveral times according to the doc of flutter rust bridge,but still got this error, and i just realized the v2 didn't exist😄

**Comment by fzyzcjy** [comment] 2023-12-18 14:44
Yes, you guys are really quick! 😆

**Comment by OnClickListener2048** [comment] 2023-12-19 06:04
> Yes, you guys are really quick! 😆 I originally thought (totally wrong!), as long as I publish v2 within a few days, nobody will realize it was once in the state that on master + not published.
> 
> Anyway I have added a temporary hint to README:
> 
> ![image](https://private-user-images.githubusercontent.com/5236035/291318305-fd58604b-cd94-4af4-b21b-f2128237021a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjU5NTcsIm5iZiI6MTcwMjk2NTY1NywicGF0aCI6Ii81MjM2MDM1LzI5MTMxODMwNS1mZDU4NjA0Yi1jZDk0LTRhZjQtYjIxYi1mMjEyODIzNzAyMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMDYwMDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM4ZGNkNDMzYWUxMWNkOTczYzQzZGVkZDBlMTM2YjUzYzQyMTkwYmIyNzA2OTVmOGZmMWVhZjYzOWYyYmNjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x5_GR6N6p7diyHqCiP07XdwwHfTntpk3QoOPEaQra08)

I really concerned about v2， I think it's a breakthrough and i really cannot wait to see it 😄

**Comment by fzyzcjy** [comment] 2023-12-19 06:23
Thank you!

P.S. 2.0.0-dev.0 is released, though I do expect it contains bugs - my PostRelease ci checker has not done yet.

**Comment by OnClickListener2048** [comment] 2023-12-19 08:48
> Thank you!
> 
> P.S. 2.0.0-dev.0 is released, though I do expect it contains bugs - my PostRelease ci checker has not done yet.

sounds great，I'm a fresher on Rust，is there a best way to learn Rust from a beginer？ what do you think

**Comment by fzyzcjy** [comment] 2023-12-19 08:49
I personally learnt Rust by https://doc.rust-lang.org/book/ and thought it is quite good, but there are many books and videos online, and IMHO different people have different books that suits the best.

**Comment by fzyzcjy** [comment] 2023-12-31 09:52
Since this issue is not a bug and solved, I will close it. Feel free to reopen!

**Closed by fzyzcjy** 2023-12-31 09:52 UTC
Labels: bug
