### ISSUE TITLE
[Bug] Cannot run successfully after codegen

### ISSUE THREAD

**Issue by jquesada2016** [fzyzcjy/flutter_rust_bridge#512] opened 2022-06-14 19:36 UTC
### Describe the bug

If we start from the template, and perform a `flutter run`, everything works fine. But as soon as one runs `just` which runs the codegen, and try to `flutter run` again, the bellow error is produced.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
export REPO_DIR="$PWD"; cd /; flutter_rust_bridge_codegen  --rust-input "$REPO_DIR/native/src/api.rs" --dart-output "$REPO_DIR/lib/bridge_generated.dart" #    --c-output "$REPO_DIR/ios/Runner/bridge_generated.h"
[2022-06-14T19:32:50Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute command: bin=powershell args=["-noprofile", "-c", "dart pub global list"] current_dir=None cmd="powershell" "-noprofile" "-c" "dart pub global list"
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] command="powershell" "-noprofile" "-c" "dart pub global list" stdout=ffigen 6.0.0
     stderr=
[2022-06-14T19:32:51Z INFO  lib_flutter_rust_bridge_codegen] Picked config: Opts { rust_input_path: "C:/Dev/flutter/projects/workbench_view/native/src/api.rs", dart_output_path: "C:/Dev/flutter/projects/workbench_view/lib/bridge_generated.dart", dart_decl_output_path: None, c_output_path: ["C:\\Users\\jose2\\AppData\\Local\\Temp\\.tmpuVMoxh.h"], rust_crate_dir: "C:/Dev/flutter/projects/workbench_view/native", rust_output_path: "C:/Dev/flutter/projects/workbench_view/native/src\\bridge_generated.rs", class_name: "Native", dart_format_line_length: 80, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/Program Files/LLVM", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "C:/Dev/flutter/projects/workbench_view/native\\Cargo.toml", dart_root: Some("C:/Dev/flutter/projects/workbench_view"), build_runner: true, exclude_sync_execution_mode_utility: false }
[2022-06-14T19:32:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-06-14T19:32:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Parse AST to IR
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\C:\\Dev\\flutter\\projects\\workbench_view\\native\\src\\api.rs"
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\C:\\Dev\\flutter\\projects\\workbench_view\\native\\src\\bridge_generated.rs"
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::parser] parse_function function name: Ident(hello)
[2022-06-14T19:32:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Transform IR
[2022-06-14T19:32:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Rust code
[2022-06-14T19:32:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Dart code
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::generator::dart] distinct_input_types=[Delegate(String), Primitive(U8), PrimitiveList(IrTypePrimitiveList { primitive: U8 })]
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::generator::dart] distinct_output_types=[Delegate(String), Primitive(U8), PrimitiveList(IrTypePrimitiveList { primitive: U8 })]
[2022-06-14T19:32:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Other things
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute format_rust path=C:/Dev/flutter/projects/workbench_view/native/src\bridge_generated.rs
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute command: bin=rustfmt args=["C:/Dev/flutter/projects/workbench_view/native/src\\bridge_generated.rs"] current_dir=None cmd="rustfmt" "C:/Dev/flutter/projects/workbench_view/native/src\\bridge_generated.rs"
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] command="rustfmt" "C:/Dev/flutter/projects/workbench_view/native/src\\bridge_generated.rs" stdout= stderr=
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute cbindgen rust_crate_dir=C:/Dev/flutter/projects/workbench_view/native c_output_path=C:\Users\jose2\AppData\Local\Temp\.tmpp0nQd1.h
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] cbindgen config: Config { header: None, includes: [], sys_includes: ["stdbool.h", "stdint.h", "stdlib.h"], after_includes: None, trailer: None, include_guard: None, pragma_once: false, no_includes: true, autogen_warning: None, include_version: false, namespace: None, namespaces: None, using_namespaces: None, braces: SameLine, line_length: 100, tab_width: 2, line_endings: LF, language: C, cpp_compat: false, style: Both, sort_by: None, usize_is_size_t: false, parse: ParseConfig { parse_deps: false, include: None, exclude: [], expand: ParseExpandConfig { crates: [], all_features: false, default_features: true, features: None, profile: Debug }, clean: false, extra_bindings: [] }, export: ExportConfig { include: [], exclude: [], rename: {}, pre_body: {}, body: {}, prefix: None, item_types: [], renaming_overrides_prefixing: false, mangle: MangleConfig { rename_types: None, remove_underscores: false } }, macro_expansion: MacroExpansionConfig { bitflags: false }, layout: LayoutConfig { packed: None, aligned_n: None }, function: FunctionConfig { prefix: None, postfix: None, must_use: None, args: Auto, rename_args: None, swift_name_macro: None, sort_by: None, no_return: None }, structure: StructConfig { rename_fields: None, derive_constructor: false, derive_eq: false, derive_neq: false, derive_lt: false, derive_lte: false, derive_gt: false, derive_gte: false, derive_ostream: false, associated_constants_in_body: false, must_use: None }, enumeration: EnumConfig { rename_variants: None, rename_variant_name_fields: SnakeCase, add_sentinel: false, prefix_with_name: false, derive_helper_methods: false, derive_const_casts: false, derive_mut_casts: false, cast_assert_name: None, must_use: None, derive_tagged_enum_destructor: false, derive_tagged_enum_copy_constructor: false, derive_tagged_enum_copy_assignment: false, derive_ostream: false, enum_class: true, private_default_tagged_enum_constructor: false }, constant: ConstantConfig { allow_static_const: true, allow_constexpr: true, sort_by: None }, defines: {}, documentation: true, documentation_style: Auto, documentation_length: Full, pointer: PtrConfig { non_null_attribute: None }, only_target_dependencies: false, cython: CythonConfig { header: None, cimports: {} } }
[2022-06-14T19:32:51Z DEBUG cbindgen::bindgen::parser] Parsing crate native
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::wire_hello.
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::wire_uint_8_list.
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::new_uint_8_list.
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::free_WireSyncReturnStruct.
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::DartPort.
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::DartPostCObjectFnType.
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::store_dart_post_cobject.
[2022-06-14T19:32:51Z INFO  cbindgen::bindgen::parser] Take native::WireSyncReturnStruct.
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute ffigen c_path=C:\Users\jose2\AppData\Local\Temp\.tmpp0nQd1.h dart_path=C:\Users\jose2\AppData\Local\Temp\.tmpx99kJc llvm_path=["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/Program Files/LLVM", "C:/msys64/mingw64"]
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] ffigen config:
            output: 'C:\Users\jose2\AppData\Local\Temp\.tmpx99kJc'
            name: 'NativeWire'
            description: 'generated by flutter_rust_bridge'
            headers:
              entry-points:
                - 'C:\Users\jose2\AppData\Local\Temp\.tmpp0nQd1.h'
              include-directives:
                - 'C:\Users\jose2\AppData\Local\Temp\.tmpp0nQd1.h'
            comments: false
            preamble: |
              // ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

            llvm-path:
               - '/opt/homebrew/opt/llvm'
               - '/usr/local/opt/llvm'
               - '/usr/lib/llvm-9'
               - '/usr/lib/llvm-10'
               - '/usr/lib/llvm-11'
               - '/usr/lib/llvm-12'
               - '/usr/lib/llvm-13'
               - '/usr/lib/llvm-14'
               - '/usr/lib/'
               - '/usr/lib64/'
               - 'C:/Program Files/llvm'
               - 'C:/Program Files/LLVM'
               - 'C:/msys64/mingw64'

[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] ffigen config_file: NamedTempFile("C:\\Users\\jose2\\AppData\\Local\\Temp\\.tmpyljZKc")
[2022-06-14T19:32:51Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute command: bin=powershell args=["-noprofile", "-c", "dart pub global run ffigen --config \"C:\\Users\\jose2\\AppData\\Local\\Temp\\.tmpyljZKc\""] current_dir=None cmd="powershell" "-noprofile" "-c" "dart pub global run ffigen --config \"C:\\Users\\jose2\\AppData\\Local\\Temp\\.tmpyljZKc\""
[2022-06-14T19:32:53Z DEBUG lib_flutter_rust_bridge_codegen::commands] command="powershell" "-noprofile" "-c" "dart pub global run ffigen --config \"C:\\Users\\jose2\\AppData\\Local\\Temp\\.tmpyljZKc\"" stdout=Running in Directory: 'C:\Program Files\Git'
    Input Headers: [C:\Users\jose2\AppData\Local\Temp\.tmpp0nQd1.h]
    Finished, Bindings generated in C:\Users\jose2\AppData\Local\Temp\.tmpx99kJc
     stderr=
[2022-06-14T19:32:53Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute format_dart path=C:/Dev/flutter/projects/workbench_view/lib/bridge_generated.dart line_length=80
[2022-06-14T19:32:53Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute command: bin=powershell args=["-noprofile", "-c", "dart format C:/Dev/flutter/projects/workbench_view/lib/bridge_generated.dart --line-length 80"] current_dir=None cmd="powershell" "-noprofile" "-c" "dart format C:/Dev/flutter/projects/workbench_view/lib/bridge_generated.dart --line-length 80"
[2022-06-14T19:32:54Z DEBUG lib_flutter_rust_bridge_codegen::commands] command="powershell" "-noprofile" "-c" "dart format C:/Dev/flutter/projects/workbench_view/lib/bridge_generated.dart --line-length 80" stdout=Formatted C:/Dev/flutter/projects/workbench_view/lib/bridge_generated.dart
    Formatted 1 file (1 changed) in 0.18 seconds.
     stderr=
[2022-06-14T19:32:54Z INFO  lib_flutter_rust_bridge_codegen] Success!
[2022-06-14T19:32:54Z INFO  flutter_rust_bridge_codegen] Now go and use it :)
←[1m# cp ios/Runner/bridge_generated.h macos/Runner/bridge_generated.h←[0m
←[1m# Uncomment this line to invoke build_runner as well←[0m
←[1m# flutter pub run build_runner build←[0m
←[1mcd native && cargo fmt←[0m
←[1m# dart format .←[0m
```

### Expected behavior

I expect the successfully generated codegen to produce non-broken code.

### Generated binding code

```dart
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports

import 'dart:convert';
import 'dart:typed_data';

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'dart:ffi' as ffi;

abstract class Native {
  Future<String> hello({required String name, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kHelloConstMeta;
}

class NativeImpl extends FlutterRustBridgeBase<NativeWire> implements Native {
  factory NativeImpl(ffi.DynamicLibrary dylib) =>
      NativeImpl.raw(NativeWire(dylib));

  NativeImpl.raw(NativeWire inner) : super(inner);

  Future<String> hello({required String name, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_hello(port_, _api2wire_String(name)),
        parseSuccessData: _wire2api_String,
        constMeta: kHelloConstMeta,
        argValues: [name],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kHelloConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "hello",
        argNames: ["name"],
      );

  // Section: api2wire
  ffi.Pointer<wire_uint_8_list> _api2wire_String(String raw) {
    return _api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  int _api2wire_u8(int raw) {
    return raw;
  }

  ffi.Pointer<wire_uint_8_list> _api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  // Section: api_fill_to_wire

}

// Section: wire2api
String _wire2api_String(dynamic raw) {
  return raw as String;
}

int _wire2api_u8(dynamic raw) {
  return raw as int;
}

Uint8List _wire2api_uint_8_list(dynamic raw) {
  return raw as Uint8List;
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class NativeWire implements FlutterRustBridgeWireBase {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void wire_hello(
    int port_,
    ffi.Pointer<wire_uint_8_list> name,
  ) {
    return _wire_hello(
      port_,
      name,
    );
  }

  late final _wire_helloPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_hello');
  late final _wire_hello = _wire_helloPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list(
    int len,
  ) {
    return _new_uint_8_list(
      len,
    );
  }

  late final _new_uint_8_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list');
  late final _new_uint_8_list = _new_uint_8_listPtr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturnStruct(
    WireSyncReturnStruct val,
  ) {
    return _free_WireSyncReturnStruct(
      val,
    );
  }

  late final _free_WireSyncReturnStructPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
          'free_WireSyncReturnStruct');
  late final _free_WireSyncReturnStruct = _free_WireSyncReturnStructPtr
      .asFunction<void Function(WireSyncReturnStruct)>();

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();
}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
```

### Generated Error from Generated Code

```shell
lib/bridge_generated.dart:142:27: Error: The parameter 'ptr' of the method 'NativeWire.store_dart_post_cobject' has type 'Pointer<NativeFunction<Bool Function(Int64, Pointer<Void>)>>', which does not match the corresponding type, 'Pointer<NativeFunction<Uint8 Function(Int64, Pointer<Void>)>>', in the overridden method, 'FlutterRustBridgeWireBase.store_dart_post_cobject'.
 - 'Pointer' is from 'dart:ffi'.
 - 'NativeFunction' is from 'dart:ffi'.
 - 'Bool' is from 'dart:ffi'.
 - 'Int64' is from 'dart:ffi'.
 - 'Void' is from 'dart:ffi'.
 - 'Uint8' is from 'dart:ffi'.
Change to a supertype of 'Pointer<NativeFunction<Uint8 Function(Int64, Pointer<Void>)>>', or, for a covariant parameter, a subtype.
    DartPostCObjectFnType ptr,
                          ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.34.2/lib/src/basic.dart:153:8: Context: This is the overridden method ('store_dart_post_cobject').
  void store_dart_post_cobject(
       ^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

### OS

Windows 11

### Version of `flutter_rust_bridge_codegen`

```
flutter_rust_bridge_codegen 1.34.2
```

### Flutter info

```
[  +60 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +88 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] cd41fdd495f6944ecd3506c21e94c6567b073278
[        ] executing: [C:\flutter/] git tag --points-at cd41fdd495f6944ecd3506c21e94c6567b073278
[  +79 ms] Exit code 0 from: git tag --points-at cd41fdd495f6944ecd3506c21e94c6567b073278
[        ] 3.0.2
[   +7 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +65 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +142 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +65 ms] Could not find a command named "doc".

[   +2 ms] Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
[  +14 ms] ensureAnalyticsSent: 3ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 64
```

### Version of `ffigen`

...I tried looking for this, but not sure where to find it, regardless, I ran this command today, so it should be the most recent version.

**Comment by fzyzcjy** [comment] 2022-06-14 20:43
So, could you please specify where it is broken, and the error messages?

**Comment by jquesada2016** [comment] 2022-06-14 20:48
Yes, of course! Sorry, I accidentally posted my issue too early and forgot to put in that small piece of info lol

**Comment by jquesada2016** [comment] 2022-06-14 20:56
@fzyzcjy I updated this issue. The error output is in the `Generated Error from Generated Code
` of the bug report.

**Comment by fzyzcjy** [comment] 2022-06-14 20:59
Duplicate of #478

**Comment by fzyzcjy** [comment] 2022-06-14 21:14
Agree. Feel free to make a PR!

**Closed** 2022-06-29 22:58 UTC
Labels: bug
