### ISSUE TITLE
[Bug] error: failed to run custom build command for `openssl-sys v0.9.87`

### ISSUE THREAD

**Issue by igor-yusupov** [fzyzcjy/flutter_rust_bridge#1204] opened 2023-05-07 17:52 UTC
### Describe the bug

When I add a tokenizers = "0.13.3" lin to Cargo.toml I got an error error: failed to run custom build command for `openssl-sys v0.9.87` while building for android.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
error: failed to run custom build command for `openssl-sys v0.9.87`
```

**Comment by erikas-taroza** [comment] 2023-05-07 19:50
Duplicate of #1171

**Closed** 2023-05-10 06:10 UTC
Labels: bug
