### ISSUE TITLE
iOS: Failed to lookup symbol (dlsym(RTLD_DEFAULT, store_dart_post_cobject)

### ISSUE THREAD

**Issue by AlienKevin** [fzyzcjy/flutter_rust_bridge#250] opened 2021-12-27 21:36 UTC
**Describe the bug**
On iOS simulator, got the following exception after calling api function:
```
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found)
```

**Additional context**
#17 talked about the same issue and said it might be caused by symbol stripping
I did some digging and found fzyzcjy's comment on an [dart-lang/ffi issue](https://github.com/dart-lang/ffi/issues/41#issuecomment-757597034). I followed the suggestion and disabled some code stripping but to no avail:
<img width="897" alt="截圖 2021-12-27 16 30 05" src="https://user-images.githubusercontent.com/22850071/147508533-78f3d65d-ccf8-4da5-97bd-41c6c9327af8.png">

**To Reproduce**
My project source code is on [GitHub](https://github.com/AlienKevin/wordshk_app)
I loaded the dylib [here](https://github.com/AlienKevin/wordshk_app/blob/fb83c720343faed193c826babaac1fc62c050e8b/lib/main.dart#L16) as instructed by the README.
And I attempted to call an api function [here](https://github.com/AlienKevin/wordshk_app/blob/fb83c720343faed193c826babaac1fc62c050e8b/lib/main.dart#L76), which triggers the exception.

Here's my build process
1. Run `cargo lipo` to create a universal binary for iOS
2. Add library output directory to **Library Search Paths** in XCode
<img width="988" alt="Library Search Path" src="https://user-images.githubusercontent.com/22850071/147507947-3c8e834d-04fb-4671-b10e-483b5d63798e.png">
3. Run `flutter run`
4. On the simulator, invoke an api function through the flutter UI

**Expected behavior**
Flutter finds and calls the api function

**Development environment (please complete the following information):**
 - OS: MacOS Monterey
 - Version 12.1
 - Version of `flutter_rust_bridge_codegen`: 1.9.1
 - Paste output of `flutter doctor -v`: No issues found
 - Version of `clang++`: Apple clang version 13.0.0 (clang-1300.0.29.30)
 - Version of `cbindgen`: 0.20.0
 - Version of `ffigen`: 4.1.2

**Smartphone, if applicable (please complete the following information):**
 - Device: iPhone 13 (iOS Simulator)
 - OS: iOS 15.2

**Comment by fzyzcjy** [comment] 2021-12-28 00:16
Yes that is about stripping... Have you tried my example in `with_flutter`?

**Comment by fzyzcjy** [comment] 2021-12-28 00:17
Moreover, please have a look at: https://github.com/fzyzcjy/flutter_rust_bridge#appendix-set-up-flutterdartrust-support

I have mentioned there, how to add things like `print("dummy_value=\(dummy_method_to_enforce_bundling())");` to enforce bundling.

**Comment by AlienKevin** [comment] 2021-12-28 03:42
Thanks for the pointer! I got it working by referencing the `with_flutter` example. I was using the **Run Flutter+Rust app** section as guidance and skipped several crucial steps during setup. The **Set up Flutter/Dart+Rust support** Appendix is really great and detailed. The only issue of the README that I see is the length and complexity. I didn't notice the appendix below because there are many instructions for different platforms all mixed together on top, along with troubleshooting, command-line options, etc.

Since there are many platform peculiarities, I think we can **increase clarity by grouping instructions based on platforms**. So Android, iOS, macOS, Windows, and Linux would each have their own README that explains set up and build as the two main sections. Pure dart can be a README on its own. And the rest of the current README, including intro, command-line, advanced, future work, and contributors can stay in the main README.

**Comment by fzyzcjy** [comment] 2021-12-28 04:19
Great. I will consider it and change it soon.

**Comment by fzyzcjy** [comment] 2022-01-01 00:56
about modifying doc: https://github.com/fzyzcjy/flutter_rust_bridge/issues/272

close this issue since it is not a bug

**Closed by fzyzcjy** 2022-01-01 00:56 UTC
Labels: bug
