### ISSUE TITLE
Supporting methods

### ISSUE THREAD

**Issue by lattice0** [fzyzcjy/flutter_rust_bridge#539] opened 2022-06-29 16:19 UTC
Just to know, isn't there support for methods?

```
pub struct MyStruct{
    something: String
}

impl MyStruct{
    fn do_something() {
        todo!()
    }
}

pub fn return_my_struct() -> MyStruct {
    todo!()
}
```

does not translate any methods.

Should I create my own pseudomethods by doing

```
pub fn my_struct_do_something(my_struct: &MyStruct) {
    //...
}
```

?

Also, I have to do

```
pub fn return_my_struct() -> MyStruct {
    todo!()
}
```

otherwise it won't create MyStruct on dart side. Is it supposed to be like this?

**Comment by fzyzcjy** [comment] 2022-06-29 22:39
Duplicate of #67

**Closed** 2022-07-15 01:12 UTC
Labels: enhancement
