### ISSUE TITLE
[Bug] generated `DartPostCObjectFnType` is not matched (`bool` vs `Uint8`) - caused by just-released `ffigen` 6.0 version

### ISSUE THREAD

**Issue by neeboo** [fzyzcjy/flutter_rust_bridge#478] opened 2022-05-30 11:27 UTC
### Describe the bug

in `FlutterRustBridgeWireBase`

```dart
abstract class FlutterRustBridgeWireBase {
  /// Not to be used by normal users, but has to be public for generated code
  // ignore: non_constant_identifier_names
  void store_dart_post_cobject(
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Uint8 Function(ffi.Int64, ffi.Pointer<ffi.Void>)>>
        ptr,
  );

  /// Not to be used by normal users, but has to be public for generated code
  // ignore: non_constant_identifier_names
  void free_WireSyncReturnStruct(WireSyncReturnStruct val);
}

```

however in `bridge_generated.dart`, type is not match

```dart
typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
```

Expected

```dart
typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Uint8 Function(DartPort, ffi.Pointer<ffi.Void>)>>;
``` 

### Codegen logs with `RUST_LOG=debug` env variable

```shell
[2022-05-30T11:19:28Z DEBUG lib_flutter_rust_bridge_codegen::commands] ffigen config:
            output: '/var/folders/0n/mlts398n6mb3hnzp_q2qsc500000gn/T/.tmpkJxhgH'
            name: 'AgentDartWire'
            description: 'generated by flutter_rust_bridge'
            headers:
              entry-points:
                - '/var/folders/0n/mlts398n6mb3hnzp_q2qsc500000gn/T/.tmpN9sofO.h'
              include-directives:
                - '/var/folders/0n/mlts398n6mb3hnzp_q2qsc500000gn/T/.tmpN9sofO.h'
            comments: false
            preamble: |
              // ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

            llvm-path:
               - '/opt/homebrew/opt/llvm'
               - '/usr/local/opt/llvm'
               - '/usr/lib/llvm-9'
               - '/usr/lib/llvm-10'
               - '/usr/lib/llvm-11'
               - '/usr/lib/llvm-12'
               - '/usr/lib/llvm-13'
               - '/usr/lib/llvm-14'
               - '/usr/lib/'
               - '/usr/lib64/'
               - 'C:/Program Files/llvm'
               - 'C:/Program Files/LLVM'
               - 'C:/msys64/mingw64'

...
[2022-05-30T11:19:29Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute format_dart path=/Users/ghostcorn/dev/agent_dart/lib/bridge/ffi/bridge_generated.dart line_length=80
[2022-05-30T11:19:29Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute command: bin=sh args=["-c", "dart format /Users/ghostcorn/dev/agent_dart/lib/bridge/ffi/bridge_generated.dart --line-length 80"] current_dir=None cmd="sh" "-c" "dart format /Users/ghostcorn/dev/agent_dart/lib/bridge/ffi/bridge_generated.dart --line-length 80"
[2022-05-30T11:19:29Z DEBUG lib_flutter_rust_bridge_codegen::commands] command="sh" "-c" "dart format /Users/ghostcorn/dev/agent_dart/lib/bridge/ffi/bridge_generated.dart --line-length 80" stdout=Formatted /Users/ghostcorn/dev/agent_dart/lib/bridge/ffi/bridge_generated.dart
    Formatted 1 file (1 changed) in 0.14 seconds.
     stderr=
[2022-05-30T11:19:29Z INFO  lib_flutter_rust_bridge_codegen] Success!
[2022-05-30T11:19:29Z INFO  flutter_rust_bridge_codegen] Now go and use it :)
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

1.32.0

**Comment by fzyzcjy** [comment] 2022-05-30 11:50
So it is problem with `Bool` vs `Uint8` I guess. bridge_generated.dart is generated by https://pub.dev/packages/ffigen so I guess it is a bug there.

Btw which `ffigen` version do you use? 6.0 (released 2hr ago), or 5.x?

**Comment by fzyzcjy** [comment] 2022-05-30 11:51
Since I see 6.0 released 2hr ago I suspect maybe it is compatibility issues so try 5.x ffigen first.

**Comment by fzyzcjy** [comment] 2022-05-30 11:51
> Booleans are now always generated with bool and ffi.Bool as it's Dart and C Type respectively. https://pub.dev/packages/ffigen/changelog

Oh, confirmed. Issue caused by 6.0 ffigen

**Comment by fzyzcjy** [comment] 2022-05-30 11:52
CI is failing as well btw

![image](https://user-images.githubusercontent.com/5236035/170986900-19aa0ffa-4b34-4ca7-ab03-a353145c9ba4.png)

**Comment by neeboo** [comment] 2022-05-30 12:41
> > Booleans are now always generated with bool and ffi.Bool as it's Dart and C Type respectively. https://pub.dev/packages/ffigen/changelog
> 
> Oh, confirmed. Issue caused by 6.0 ffigen

Thanks for the quick reply, it's 6.0 indeed

**Comment by dbsxdbsx** [comment] 2022-06-03 03:35
I got the issue too. I guess the only work round is to just downgrade `ffigen` to 5.0 before new version of `frb`.

**Comment by ozanmuyes** [comment] 2022-06-05 00:13
How to downgrade `ffigen`?

**Comment by fzyzcjy** [comment] 2022-06-05 00:35
ffigen is nothing but a standard dart/flutter library :)

**Comment by ozanmuyes** [comment] 2022-06-05 01:28
Yes, thanks but I'm nothing but a newbie. Interestingly on Dart and Rust - but I'm fluent with Flutter 😜.

Here's how for those who like me;

1. Deactivate ffigen@6 via

   ```shell
   dart pub global deactivate ffigen
   ```

2. Optional - Remove ffigen@6

   Locate the "pub cache" [depending on your OS]() and remove the globally deactivated dependency, e.g. for MacOS run;
   ```shell
   rm -rf ~/.pub-cache/hosted/pub.dartlang.org/ffigen-6.0.0
   ```

3. Globally install and activate ffigen@5

   ```shell
   dart pub global activate ffigen 5.0.1
   ```

**Comment by TheAifam5** [comment] 2022-06-25 21:56
Downgrading to 5.0.1 does not work on my machine due to LLVM 14 libs living in lib64 and somehow 5.0 cannot find libclang but 6.0 can find them (maybe has been fixed in 6.0). I feel like I am stuck. Using Gentoo no-multilib. :(

**Comment by fzyzcjy** [comment] 2022-06-25 22:50
@TheAifam5 Feel free to make a PR! It should be fairly simple to fix it

**Comment by blelump** [comment] 2022-06-28 09:42
@fzyzcjy 

How to actually understand this problem with `ffigen` or how it should be fixed/where? So in essence is it a problem with `flutter_rust_bridge` and how it is using `ffigen` or the problem lies in the `ffigen` itself?

**Comment by fzyzcjy** [comment] 2022-06-28 12:19
@blelump 

in ffigen 6.0, "Booleans are now always generated with bool and ffi.Bool as it's Dart and C Type respectively." https://pub.dev/packages/ffigen/changelog

But in flutter_rust_bridge we have used the old (5.x) signature, use uint8 instead of bool.

**Closed** 2022-06-29 22:58 UTC
Labels: bug
