### ISSUE TITLE
Issues while trying to automatically convert third-party packages

### ISSUE THREAD

**Issue by furtidev** [fzyzcjy/flutter_rust_bridge#2382] opened 2024-11-01 19:51 UTC
### Describe the bug

I'm using 3 thirdparty packages in my Rust code, `serde`, `quick-xml` and `serde-value`. While `serde` successfully generates (with warnings about merging, that it may be an issue if the merged code was actually needed) the other two straight up fail.

### Steps to reproduce

1. Use the flutter_rust_bridge default template to create a new project.
2. Add the following crates to `rust/Cargo.toml`:
    ```toml
    [dependencies]
   flutter_rust_bridge = "=2.5.1"
   serde = { version = "1.0.210", features = ["derive"] }
   quick-xml = { version = "0.36.2", features = ["serialize"] }
   serde-value = "0.7.0"
   ```
3. Update `flutter_rust_bridge.yaml`:
   ```yaml
   rust_input: crate::api,serde,quick-xml,serde-value
   ...
   ```
4. Run `flutter_rust_bridge_codegen generate`

### Logs
[logs.txt](https://github.com/user-attachments/files/17603615/logs.txt)

### Expected behavior

I expected the CLI to generate code for all the third-party dependencies successfully.

### OS

Linux EndeavourOS

### Version of `flutter_rust_bridge_codegen`

2.5.1

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.24.3, on EndeavourOS 6.11.3-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.24.3 on channel stable at /home/furtidev/Programming/thirdparty/flutter-dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (7 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/furtidev/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/furtidev/Programming/thirdparty/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.5
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/furtidev/Programming/thirdparty/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • EndeavourOS 6.11.3-arch1-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Version of `clang++`

18.1.8

**Comment by fzyzcjy** [comment] 2024-11-01 23:15
Yes, I would expect too complex 3rd party crates to fail when using this experimental feature, because Rust is such a feature-rich language that it is hard to cover everything - that's why it is called "experimental"! You can always fall back to the manual approach to mirror 3rd party crates, or PR to enhance the auto scanner.

**Comment by furtidev** [comment] 2024-11-02 09:39
@fzyzcjy I'm a bit worried though, do I really have to rewrite the signature of all code in these libraries? Or only the ones that are relevant to the Rust -> Dart interop?

**Comment by fzyzcjy** [comment] 2024-11-02 10:31
@furtidev You can write manually for the APIs that you use. Or, as mentioned above, you can try to see where frb's experimental fully auto mode fails and fix/workaround it. 

But I guess serde_value may be too hard to be translated, since it requires quite complex callbacks etc.

**Comment by furtidev** [comment] 2024-11-02 10:34
@fzyzcjy so it'll be hard to work with even if I try doing it manually?

**Comment by fzyzcjy** [comment] 2024-11-02 10:36
@furtidev Depending on what you need. You can quickly glance at frb's doc to see what is supported (a lot!), but some Rust features may still not be supported since there are really so many features.

**Comment by furtidev** [comment] 2024-11-02 10:38
@fzyzcjy Thank you!

**Comment by fzyzcjy** [comment] 2024-11-02 10:44
Feel free to ping me if you have any questions!

**Comment by furtidev** [comment] 2024-11-02 12:52
@fzyzcjy The one common error I got is: `Can't use 'gender' because it is declared more than once.`

`gender` is a parameter in a struct. There are other similar errors, about other parameters. I'm not sure why this is happening or how can something existing more than once cause an error.

**Comment by furtidev** [comment] 2024-11-02 15:07
I've realized what happened, I think. My struct has some parameters which have different casing: `gender`, `Gender`, `isEfficient`, `IsEfficient` - the translator ignored these subtle changes, thus the duplication errors.

**Comment by fzyzcjy** [comment] 2024-11-02 23:21
> My struct has some parameters which have different casing: gender, Gender, isEfficient, IsEfficient

Ah I guess so! frb tries to rename it to follow naming convention of each language.

> Those differently cased parameters do need to exist.

I wonder what is your use case? Often I heard people saying such naming may be a little be confusing to users.

Btw you can check `#[frb(name = ...)]` to see whether it helps.

**Comment by furtidev** [comment] 2024-11-02 23:39
It's a Stardew Valley savefile parser, so we have to adhere all it's quirks. It's late for me, so I'll check out `#[frb(name = ...)]` tomorrow.

**Comment by fzyzcjy** [comment] 2024-11-03 01:34
I see... That's really weird...

**Comment by furtidev** [comment] 2024-11-03 14:38
This is weird,
```rust
error[E0412]: cannot find type `SaveGame` in this scope
   --> src/frb_generated.rs:284:51
    |
284 | impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<SaveGame>> for SaveGame {
    |                                                   ^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
28  + use rusty_walnut::structs::savegame::SaveGame;
    |
```
The compiler knows where it is, but FRB doesn't inject that one-line no matter what.

**Comment by fzyzcjy** [comment] 2024-11-03 23:17
> The issue is that the SaveGameImpl class doesn't have any of it's original fields from Rust, it's just empty.

Do you mean it is opaque instead of non-opaque?

**Comment by furtidev** [comment] 2024-11-03 23:27
> > The issue is that the SaveGameImpl class doesn't have any of it's original fields from Rust, it's just empty.
> 
> Do you mean it is opaque instead of non-opaque? (or something else) Maybe paste the generate SaveGame & SaveGameImpl code to have a brief look.

`SaveGame` is opaque, yes.
```rust
// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SaveGame>>
abstract class SaveGame implements RustOpaqueInterface {}
```
And here's the generated file:
[frb_generated.dart.txt](https://github.com/user-attachments/files/17612496/frb_generated.dart.txt)

And here's my API code:
```rust
use flutter_rust_bridge::frb;
pub use rusty_walnut::*;
pub use rusty_walnut::structs::savegame::SaveGame;

#[frb(init)]
pub fn init_app() {
    flutter_rust_bridge::setup_default_user_utils();
}

pub fn load_savefile(file_path: &str) -> Option<SaveGame> {
	let savegame_result = parse_savefile(file_path);
	match savegame_result {
		Ok(s) => {
			Some(s)
		}
		Err(e) => {
			eprintln!("{}", e);
			None
		}
	}
}
```

**Comment by fzyzcjy** [comment] 2024-11-04 13:02
If you manually handle third party types (instead of auto scan), then if you want non-opaque types, you need to do mirroring.

> because I realized I didn't need to access them from Dart, so, there was no need to convert serde and quick-xml

Looks great!

**Comment by furtidev** [comment] 2024-11-04 13:32
> If you manually handle third party types (instead of auto scan), then if you want non-opaque types, you need to do mirroring.
> 
> > because I realized I didn't need to access them from Dart, so, there was no need to convert serde and quick-xml
> 
> Looks great!

I did add the `rusty_walnut` crate for auto scanning:
```yaml
# flutter_rust_bridge.yaml
rust_input: crate::api, crate::rusty_walnut
...
```
But perhaps this is wrong?

**Comment by fzyzcjy** [comment] 2024-11-04 14:09
Hmm, if it does not work, then maybe "use crate A's non-opaque struct in crate B" is not implemented yet in this experimental feature...

**Comment by fzyzcjy** [comment] 2024-11-05 00:40
> from crate::rusty_walnut to rusty_walnut

Oh you are right! `crate::rusty_walnut` means your firstly-party crate's subfolder!

**Comment by fzyzcjy** [comment] 2024-11-05 00:40
> What's wrong? Something about trait bounds not being satisfied.

Looks like a bug. Feel free to isolate the problem (i.e. make a reproducible sample), then I can fix it.

**Comment by furtidev** [comment] 2024-11-05 11:13
> Looks like a bug. Feel free to isolate the problem (i.e. make a reproducible sample), then I can fix it.

Sure, here's the code, there's not much here expect my own library (`rust/src/rusty_walnut`) and some code to access from Dart (`rust/src/api/minimal.rs`), so I suppose it's already isolated enough. 
[dart_minimal.zip](https://github.com/user-attachments/files/17631431/dart_minimal.zip)
Though, one thing to note, you need to replace it with `flutter_rust_bridge/frb_examples/dart_minimal` on a locally cloned repo - it relies on a lot of relative paths for dependencies (I basically built on top of that example).

**Comment by fzyzcjy** [comment] 2024-11-05 11:28
Thanks, could you please make it on github for easier access? (For example, since you mention modifying dart_minimal, the simplest way is to fork frb and modify and link it here)

**Comment by furtidev** [comment] 2024-11-05 13:48
> Thanks, could you please make it on github for easier access? (For example, since you mention modifying dart_minimal, the simplest way is to fork frb and modify and link it here)

Yes, of course: https://github.com/furtidev/flutter_rust_bridge

**Comment by fzyzcjy** [comment] 2024-11-05 23:27
I glanced at it, but it does not seem to be a minimal reproducible sample. Could you please make it minimal? Usually, it can be done by removing unrelated parts, and ultimately we will get a very short example of only a dozen line, and can even be copy-pasted here.

**Comment by fzyzcjy** [comment] 2024-11-07 03:40
Great! Could you please further simplify a bit to isolate the cause? e.g. if it is related to option box, then this should have error:

```
pub struct FirstEntry {
    pub Item: Option<Box<FirstEntry>>,
}
```

**Comment by hitblast** [comment] 2024-11-07 05:12
@fzyzcjy Alright! I've pushed the latest code with the changes you requested. Note that the `example_xml` file only contains the keys as of now, since due to the minification, only the `FirstEntry` key is active.

**Comment by fzyzcjy** [comment] 2024-11-07 05:34
Great! Briefly looked at the code (not debug yet). A quick workaround: what if we have a function `pub dummy_function() -> FirstEntry` in `api/minimal.rs`?

**Comment by hitblast** [comment] 2024-11-07 06:01
@fzyzcjy Well, I'm not quite sure about the approach but the output should be the same since the types are identical.

**Comment by fzyzcjy** [comment] 2024-11-07 07:16
Ok then that workaround does not work.

> since the types are identical.

IMHO no. The current code is `pub fn load_xml_file(file_path: &str) -> Option<XmlReadout>`, thus `FirstEntry` is only indirectly used. I was wondering whether a *direct* usage will workaorund it.

I will look at it later in the next batch. Alternatively, feel free to debug and PR!

**Comment by hitblast** [comment] 2024-11-07 07:58
> Ok then that workaround does not work.
> 
> > since the types are identical.
> 
> IMHO no. The current code is `pub fn load_xml_file(file_path: &str) -> Option<XmlReadout>`, thus `FirstEntry` is only indirectly used. I was wondering whether a _direct_ usage will workaorund it.
> 
> I will look at it later in the next batch. Alternatively, feel free to debug and PR!

I've just now tried wrapping `FirstEntry` in a direct use case, still the same error, so the workaround indeed doesn't work. By the way, thanks for looking into this! Hopefully it'll be resolved.

**Comment by fzyzcjy** [comment] 2024-11-07 10:08
To be fixed by https://github.com/fzyzcjy/flutter_rust_bridge/pull/2398****

**Closed** 2024-11-07 12:09 UTC
Labels: awaiting, experimental feature

**Comment by furtidev** [comment] 2024-11-07 15:55
@fzyzcjy yay! it works now! thanks for all your help

**Comment by fzyzcjy** [comment] 2024-11-07 23:16
You are welcome!

Since 2.6.0 was released just two days ago, it may be good to wait some time before releasing next one. Could you please use the master version temporarily? (It should be of the same quality as released version, since we have the same CI checks).
